/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_github_morningwn_tools_utils_WinUtils */

#ifndef _Included_com_github_morningwn_tools_utils_WinUtils
#define _Included_com_github_morningwn_tools_utils_WinUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_morningwn_tools_utils_WinUtils
 * Method:    setWallpaper
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_morningwn_tools_utils_WinUtils_setWallpaper
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
